"""Regression test: per_particle_analysis.py CLI must produce numerically
identical CSV output (drop ID columns, sort rows, integer exact-equal,
float np.allclose) before and after the U4 refactor.

The committed expected CSVs under tests/fixtures/per_particle/{group}_expected/
were generated by the UNMODIFIED CLI (commit 2fc52106). Every refactor step
in U4 must keep this test green.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "per_particle"
CLI = REPO_ROOT / "per_particle_analysis.py"


def _run_cli(args: list[str], cwd: Path) -> None:
    """Invoke the CLI; raise with stdout+stderr on non-zero exit."""
    cmd = [sys.executable, str(CLI), *args]
    result = subprocess.run(
        cmd, cwd=str(cwd), capture_output=True, text=True
    )
    if result.returncode != 0:
        raise AssertionError(
            f"CLI exited {result.returncode}\n"
            f"cmd: {' '.join(cmd)}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )


def _assert_numeric_parity(actual_csv: Path, expected_csv: Path,
                           sort_key: str) -> None:
    """Compare two CSVs with the numeric-parity rule.

    - Drop the `group` column if present (it carries a path-derived id
      and differs between CLI and framework callers; the test focuses
      on the scientific values).
    - Sort rows by `sort_key`.
    - Reset index.
    - For integer columns: exact equality.
    - For float columns: np.allclose with rtol=1e-10 atol=0, equal_nan=True.
    """
    assert actual_csv.exists(), f"actual missing: {actual_csv}"
    assert expected_csv.exists(), f"expected missing: {expected_csv}"

    actual = pd.read_csv(actual_csv)
    expected = pd.read_csv(expected_csv)

    if "group" in actual.columns:
        actual = actual.drop(columns=["group"])
    if "group" in expected.columns:
        expected = expected.drop(columns=["group"])

    actual = actual.sort_values(sort_key).reset_index(drop=True)
    expected = expected.sort_values(sort_key).reset_index(drop=True)

    assert list(actual.columns) == list(expected.columns), (
        f"column mismatch\nactual:   {list(actual.columns)}\n"
        f"expected: {list(expected.columns)}"
    )
    assert len(actual) == len(expected), (
        f"row count mismatch: actual={len(actual)} expected={len(expected)}"
    )

    for col in actual.columns:
        a = actual[col]
        e = expected[col]
        # Integer-like columns: both should be ints (or coercible)
        if pd.api.types.is_integer_dtype(e):
            pd.testing.assert_series_equal(
                a.astype(e.dtype), e, check_dtype=False, check_exact=True,
                obj=f"column {col!r}",
            )
        elif pd.api.types.is_float_dtype(e):
            np.testing.assert_allclose(
                a.values, e.values, rtol=1e-10, atol=0.0, equal_nan=True,
                err_msg=f"float column {col!r} mismatch",
            )
        else:
            # Object or other; require exact equality (strings, etc.)
            pd.testing.assert_series_equal(
                a, e, check_dtype=False, check_exact=True,
                obj=f"column {col!r}",
            )


def test_cli_group_a_pbody_only(tmp_path: Path) -> None:
    """group_a is P-body-only (no SG/cp_mask files)."""
    out_p = tmp_path / "out_pbody.csv"
    out_s = tmp_path / "out_sg.csv"
    _run_cli([
        "--data-dir", str(FIXTURE_ROOT / "group_a"),
        "--output-pbody", str(out_p),
        "--output-sg", str(out_s),
        "--no-bgsub",
    ], cwd=REPO_ROOT)

    _assert_numeric_parity(
        out_p,
        FIXTURE_ROOT / "group_a_expected" / "combined_pbody.csv",
        sort_key="pbody_id",
    )
    # No SG outputs expected; the CLI does not create an SG CSV when no SGs
    # exist in any group. The expected file is also absent.
    assert not out_s.exists()


def test_cli_group_b_both_branches(tmp_path: Path) -> None:
    """group_b has both P-body + SG (with deliberate spatial overlap)."""
    out_p = tmp_path / "out_pbody.csv"
    out_s = tmp_path / "out_sg.csv"
    _run_cli([
        "--data-dir", str(FIXTURE_ROOT / "group_b"),
        "--output-pbody", str(out_p),
        "--output-sg", str(out_s),
        "--no-bgsub",
    ], cwd=REPO_ROOT)

    _assert_numeric_parity(
        out_p,
        FIXTURE_ROOT / "group_b_expected" / "combined_pbody.csv",
        sort_key="pbody_id",
    )
    _assert_numeric_parity(
        out_s,
        FIXTURE_ROOT / "group_b_expected" / "combined_sg.csv",
        sort_key="sg_id",
    )


def test_cli_group_b_single_cell(tmp_path: Path) -> None:
    """group_b with --single-cell mode (cp_mask aggregation)."""
    out_p = tmp_path / "out_pbody.csv"
    out_s = tmp_path / "out_sg.csv"
    _run_cli([
        "--data-dir", str(FIXTURE_ROOT / "group_b"),
        "--output-pbody", str(out_p),
        "--output-sg", str(out_s),
        "--no-bgsub",
        "--single-cell",
    ], cwd=REPO_ROOT)

    _assert_numeric_parity(
        out_p,
        FIXTURE_ROOT / "group_b_expected" / "sc_pbody.csv",
        sort_key="cell_id",
    )
    _assert_numeric_parity(
        out_s,
        FIXTURE_ROOT / "group_b_expected" / "sc_sg.csv",
        sort_key="cell_id",
    )
