"""Regression test: per_particle_multichannel.py CLI must produce numerically
identical CSV output to the committed baseline (generated by the UNMODIFIED
original CLI before the U3 pure-core extraction).

Mirrors tests/test_scripts/test_per_particle_regression.py: run the repo-root
CLI via subprocess and compare each output CSV to its committed expected CSV
with the numeric-parity rule (drop the path-derived `group` id, sort rows,
integer exact-equal, float np.allclose).
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "per_particle_multichannel"
CLI = REPO_ROOT / "per_particle_multichannel.py"


def _run_cli(args: list[str]) -> None:
    cmd = [sys.executable, str(CLI), *args]
    result = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True,
                            text=True)
    if result.returncode != 0:
        raise AssertionError(
            f"CLI exited {result.returncode}\ncmd: {' '.join(cmd)}\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )


def _assert_numeric_parity(actual_csv: Path, expected_csv: Path,
                           sort_key: str) -> None:
    assert actual_csv.exists(), f"actual missing: {actual_csv}"
    assert expected_csv.exists(), f"expected missing: {expected_csv}"

    actual = pd.read_csv(actual_csv)
    expected = pd.read_csv(expected_csv)

    if "group" in actual.columns:
        actual = actual.drop(columns=["group"])
    if "group" in expected.columns:
        expected = expected.drop(columns=["group"])

    # Normalize column order so a column-ordering difference never masks a
    # numeric one (and vice versa).
    actual = actual.reindex(columns=sorted(actual.columns))
    expected = expected.reindex(columns=sorted(expected.columns))

    actual = actual.sort_values(sort_key).reset_index(drop=True)
    expected = expected.sort_values(sort_key).reset_index(drop=True)

    assert list(actual.columns) == list(expected.columns), (
        f"column mismatch\nactual:   {list(actual.columns)}\n"
        f"expected: {list(expected.columns)}"
    )
    assert len(actual) == len(expected), (
        f"row count mismatch: actual={len(actual)} expected={len(expected)}"
    )

    for col in actual.columns:
        a = actual[col]
        e = expected[col]
        if pd.api.types.is_integer_dtype(e):
            pd.testing.assert_series_equal(
                a.astype(e.dtype), e, check_dtype=False, check_exact=True,
                obj=f"column {col!r}",
            )
        elif pd.api.types.is_float_dtype(e):
            np.testing.assert_allclose(
                a.values, e.values, rtol=1e-10, atol=0.0, equal_nan=True,
                err_msg=f"float column {col!r} mismatch",
            )
        else:
            pd.testing.assert_series_equal(
                a, e, check_dtype=False, check_exact=True,
                obj=f"column {col!r}",
            )


def test_cli_group_a_per_particle(tmp_path: Path) -> None:
    """group_a: per-particle, two channels, no cp_mask."""
    out = tmp_path / "out.csv"
    _run_cli(["--data-dir", str(FIXTURE_ROOT / "group_a"),
              "--output", str(out)])
    _assert_numeric_parity(
        out, FIXTURE_ROOT / "group_a_expected" / "combined.csv",
        sort_key="particle_id",
    )


def test_cli_group_b_per_particle_with_cell_id(tmp_path: Path) -> None:
    """group_b: per-particle with a cp_mask present → rows carry cell_id."""
    out = tmp_path / "out.csv"
    _run_cli(["--data-dir", str(FIXTURE_ROOT / "group_b"),
              "--output", str(out)])
    df = pd.read_csv(out)
    assert "cell_id" in df.columns  # cp_mask present, single_cell off
    _assert_numeric_parity(
        out, FIXTURE_ROOT / "group_b_expected" / "combined.csv",
        sort_key="particle_id",
    )


def test_cli_group_b_single_cell(tmp_path: Path) -> None:
    """group_b: --single-cell aggregation + whole-cell stats."""
    out = tmp_path / "out.csv"
    _run_cli(["--data-dir", str(FIXTURE_ROOT / "group_b"),
              "--output", str(out), "--single-cell"])
    _assert_numeric_parity(
        out, FIXTURE_ROOT / "group_b_expected" / "sc.csv",
        sort_key="cell_id",
    )
