"""Regression test: whole_field_analysis.py CLI must produce numerically
identical CSV output to the committed baseline (generated by the UNMODIFIED
original CLI before the U6 pure-core extraction) for presets v2-v5, including
single-cell two-region and three-region modes.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "whole_field_intensity"
CLI = REPO_ROOT / "whole_field_analysis.py"


def _run_cli(args: list[str]) -> None:
    cmd = [sys.executable, str(CLI), *args]
    result = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True,
                            text=True)
    if result.returncode != 0:
        raise AssertionError(
            f"CLI exited {result.returncode}\ncmd: {' '.join(cmd)}\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )


def _assert_numeric_parity(actual_csv: Path, expected_csv: Path,
                           sort_key: str) -> None:
    actual = pd.read_csv(actual_csv)
    expected = pd.read_csv(expected_csv)

    if "group" in actual.columns:
        actual = actual.drop(columns=["group"])
    if "group" in expected.columns:
        expected = expected.drop(columns=["group"])

    actual = actual.reindex(columns=sorted(actual.columns))
    expected = expected.reindex(columns=sorted(expected.columns))
    actual = actual.sort_values(sort_key).reset_index(drop=True)
    expected = expected.sort_values(sort_key).reset_index(drop=True)

    assert list(actual.columns) == list(expected.columns), (
        f"column mismatch\nactual:   {list(actual.columns)}\n"
        f"expected: {list(expected.columns)}"
    )
    assert len(actual) == len(expected)
    for col in actual.columns:
        a, e = actual[col], expected[col]
        if pd.api.types.is_integer_dtype(e):
            pd.testing.assert_series_equal(
                a.astype(e.dtype), e, check_dtype=False, check_exact=True,
                obj=f"column {col!r}",
            )
        elif pd.api.types.is_float_dtype(e):
            np.testing.assert_allclose(
                a.values, e.values, rtol=1e-10, atol=0.0, equal_nan=True,
                err_msg=f"float column {col!r} mismatch",
            )
        else:
            pd.testing.assert_series_equal(
                a, e, check_dtype=False, check_exact=True, obj=f"column {col!r}"
            )


@pytest.mark.parametrize("preset", ["v2", "v3", "v4", "v5"])
def test_cli_preset_whole_field(tmp_path: Path, preset: str) -> None:
    out = tmp_path / "out.csv"
    _run_cli(["--preset", f"decapping-sensor-{preset}",
              "--data-dir", str(FIXTURE_ROOT), "--output", str(out)])
    # Whole-field rows have no unique id column; sort by pbody_area_px (stable
    # for a single-row field) — there is exactly one row per field.
    _assert_numeric_parity(
        out, FIXTURE_ROOT / "expected" / f"{preset}.csv",
        sort_key="pbody_area_px",
    )


@pytest.mark.parametrize("preset", ["v2", "v4"])
def test_cli_preset_single_cell(tmp_path: Path, preset: str) -> None:
    out = tmp_path / "out.csv"
    _run_cli(["--preset", f"decapping-sensor-{preset}", "--single-cell",
              "--data-dir", str(FIXTURE_ROOT), "--output", str(out)])
    _assert_numeric_parity(
        out, FIXTURE_ROOT / "expected" / f"{preset}_sc.csv",
        sort_key="cell_id",
    )
